version: '3'

includes:
  vars: vars.yml

tasks:
  server:
    cmds:
      - go run -ldflags="{{.LD_FLAGS}}" main.go server

  build:
    cmds:
      - go build -o {{.BIN_PATH}}/app -ldflags="{{.LD_FLAGS}}" main.go

  test:
    cmds:
      - go test -race ./...

  lint:
    cmds:
      - golangci-lint run --config=.golangci.yml ./...


  checkpoint:
    cmds:
      - git add .
      - git commit -a -m "checkpoint $(date +'%Y-%m-%d %H:%M:%S')"
